# Generated by Django 5.0 on 2023-12-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDataBank', '0003_student_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_statement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
