# Generated by Django 4.2.8 on 2023-12-17 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDataBank', '0005_score_delete_task_remove_user_email_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(default='default_username', on_delete=django.db.models.deletion.CASCADE, to='StudentDataBank.user'),
        ),
    ]
