# Generated by Django 4.2.8 on 2023-12-17 07:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDataBank', '0006_score_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
